import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { ContextProvider, QueryProvider, ToastProvider } from '../providers'

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SMC - SwiftCare Connec+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en" suppressHydrationWarning>
      <body className={`${lexend.className} h-full`}>
        <ToastProvider />
        <QueryProvider>
          <ContextProvider>
            {children}
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
